language: node_js
node_js:
  - 16
services:
  - docker
# Pre-testing installs
install:
  - echo "rien à installer"
# Scripts to be run such as tests
before_script:
  - echo "aucun test"

script:
  - cd udagram-api-feed && docker build -t udagram-api-feed .
  - docker tag udagram-api-feed hakouabh/udagram-api-feed:latest && cd ..
  - cd udagram-api-user && docker build -t udagram-api-user .
  - docker tag udagram-api-user hakouabh/udagram-api-user:latest && cd ..
  - cd udagram-frontend && docker build -t udagram-frontend .
  - docker tag udagram-frontend hakouabh/udagram-frontend:latest && cd ..
  - cd udagram-reverseproxy && docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy hakouabh/udagram-reverseproxy:latest && cd ..

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push hakouabh/udagram-api-feed:latest
  - docker push hakouabh/udagram-api-user:latest
  - docker push hakouabh/udagram-frontend:latest
  - docker push hakouabh/udagram-reverseproxy:latest
